import { Layout } from '../components/layout/Layout';

export default function Home(): JSX.Element {
  return (
    <Layout title="Pota Next Template" description="Generated by create-pota">
      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Pota&apos;s Next.js!</a>
        </h1>

        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>
      </main>
    </Layout>
  );
}
